#!/bin/bash
for i in ../*/ ;
do
	echo $i;
	cd $i;
	git pull;
	cd ../Lang;
done
cloc ../ > statistic.txt ; 
sed -e '1,5d' < statistic.txt > statistic_filtered.txt ;
git init
git add -A
git commit -m "first commit"
git remote add origin https://github.com/Alex-Tsvetanov/Lang.git
git push -u origin master
